### ISSUE TITLE
Mod Request - Steves Factory Manager

### ISSUE THREAD

**Issue by aepod** [Amaxter/Core-Zero#11]
Please add this to the pack, it makes for some very easy automation, and comes with a really cool gui.

http://minecraft.curseforge.com/mc-mods/228626-steves-factory-manager

Also, if you add that.. try to add http://minecraft.curseforge.com/mc-mods/226067-steves-addons
The add-ons give you a couple extra things.

**Comment by Amaxter** [comment]
For next update maybe :), leaving open to remind myself.

**Comment by Amaxter** [comment]
Done in the new update.
