### ISSUE TITLE
Player getting reset on server restart

### ISSUE THREAD

**Issue by tasgon** [Amaxter/Core-Zero#15]
Every single time I connect back to the server after it restarts, I get sent back to spawn with only spawn items in my inventory, as if I had connected to the server for the first time. Do you know what could be causing this?

Thanks in advance!

**Comment by Amaxter** [comment]
That is very odd, it must be forgetting your playerdata. I will look into it.

**Comment by druv5319** [comment]
Since you just started the server, its possible due to the rollbacks from the crashes

**Comment by Amaxter** [comment]
We're looking into the rollbacks, perhaps we will do another world reset.

**Comment by druv5319** [comment]
thank you, id rather have a world reset than having rollbacks every 15 mins
