### ISSUE TITLE
Instant gamecrash after world load

### ISSUE THREAD

**Issue by zerogott** [Amaxter/Core-Zero#18]
Hey,
my game keeps crashing after i killed of the "golems" for the dark purple gems things
crashlog http://pastebin.com/T17bX9un

**Comment by Amaxter** [comment]
Ah, I need to disable Colossi, they just cause problems. Will close this issue once I update and disable them.

**Comment by zerogott** [comment]
wow
thanks for the fast support :)

**Comment by Amaxter** [comment]
No problem :). To fix your issue now restore from the latest Aroma Backup (backups folder in the folder for the modpack in your .technic).

**Comment by zerogott** [comment]
thanks worked :+1:
