### ISSUE TITLE
Pseudo-Inversion Sigil Issue.

### ISSUE THREAD

**Issue by TheChiller12** [Amaxter/Core-Zero#19]
So I have gained the Psuedo-Inversion Sigil, which should give you the ability to create "stackable stable" unstable ingots. Before the server reset, this item was working fine. However, after the reset, I can no longer create the special stable ingots. I do not know how this happened, but please fix this!

**Comment by Amaxter** [comment]
Please submit the issue to the Extra Utilities GitHub.

**Comment by Amaxter** [comment]
Make sure you're doing the ritual properly.

**Comment by Amaxter** [comment]
Until

**Comment by Amaxter** [comment]
It's an issue with Extra Utilities from the looks, will close this when RWTema fixes in an update.

**Comment by TheChiller12** [comment]
Saw this in a comment on my issue on the Extra Utilities GitHub...

MrPotatoGaming commented 3 days ago
Have you tried reproducing this in single player?
Does it work with just Extra Utilities? \* Yes it does. It works fine in my pack.
What version of the mod are you using?

Basically - you have some mod that is causing a conflict. My assumption is that your pack has Ganys Surface in it. Please update to the newest version of Ganys Surface, and then go to the config and disable the options relating to "No Conflict" as these break the Unstable recipes.

**Comment by Amaxter** [comment]
Ok, will do that for next update. Thanks for the info.

**Comment by TheChiller12** [comment]
Glad I could help! :D Temporarily closing this unless the solution provided doesn't work. I'll try it in SP and see if it works.

**Comment by Amaxter** [comment]
Wanna know something cool? For the future if there's another issue that can be solved via config modifications and you know it, there's a config folder on this GitHub, make a pull request with your changes after making an edit to the config it relates to and if I approve it will be in the master branch for the next update :)

**Comment by TheChiller12** [comment]
Really? Wow, I'll make sure to do that next time. Never used github until now. :P

**Comment by Amaxter** [comment]
You learn somethign new every day :D
