### ISSUE TITLE
Dimensional Doors dungeons seem to cause server lag

### ISSUE THREAD

**Issue by tasgon** [Amaxter/Core-Zero#22]
Try disabling the worldgen of those.

**Comment by Amaxter** [comment]
Do you have any evidence or more specific details?

**Comment by Amaxter** [comment]
Closing until you provide some real evidence and more specific details than "lag".

**Comment by tasgon** [comment]
I went through a couple of them and I noticed that the chunk generation slowed significantly as I went deeper through the dungeons. It also took more time for the door to 'realize' that I had walked through it. At one point, the server crashed just after I went through a dimensional door. It could have been just a coincidence, as DDoors is designed to be optimized for servers, but it also may be causing crashes.

**Comment by Amaxter** [comment]
I will look into it.

**Comment by xJon** [comment]
Can you please provide a crash report, and/or a fml-server-latest.log?
We need more info.

**Comment by Amaxter** [comment]
Until you provide more information I will have to close this issue.
