### ISSUE TITLE
Quest issue

### ISSUE THREAD

**Issue by shugnk** [Amaxter/Core-Zero#23]
The quests on my client got messed up or something. When I finished all the primary quests in the first chapter, I couldnt start the next chapter. I didnt have the option too or anything like that. I even tried to edit the quests to make them playable but to no avail. So the trigger to the second chapter wasnt working or something along those lines. I tried also to reset all my quests and go back with the OP quest book at get back to the same quest it stopped me at. It also glitched up and I could only get to half of the first chapter. It wouldnt allow the other quests to show up.

**Comment by shugnk** [comment]
made a separate issue

**Comment by Amaxter** [comment]
Thanks.

**Comment by xJon** [comment]
If you changed the quests simply redownload the modpack (backup your saves!) and it'll override your edited quests to the normal ones.

**Comment by shugnk** [comment]
alright will do
