### ISSUE TITLE
Magnetic force

### ISSUE THREAD

**Issue by druv5319** [Amaxter/Core-Zero#24]
Can you please ban this item on the server? It makes people tp to other without them noticing. I now feel like someone is always at my base and taking stuff. Can you please ban the magnetic force?

**Comment by Amaxter** [comment]
You already opened this issue, be patient, I'm on vacation. Thanks.

**Comment by druv5319** [comment]
What about Jon?

**Comment by Amaxter** [comment]
He's busy right now with The 1.7.10 Pack.
