### ISSUE TITLE
server problems again!

### ISSUE THREAD

**Issue by hubb2001** [Amaxter/Core-Zero#25]
once again the server is rolling back only a few days after the reset
# fixtherollbacks

**Comment by druv5319** [comment]
If you can fix this can, can there be a way without resetting the server again?

**Comment by Amaxter** [comment]
1) please stop using hashtags, this is GitHub, not a social network.

2) sorry, it's not an issue we are capable of fixing in the near future. Closing this, as its server related and no modpack related.
