### ISSUE TITLE
Travel anchor glitch

### ISSUE THREAD

**Issue by hubb2001** [Amaxter/Core-Zero#26]
the private setting on travel anchors do not work 
when set to private an anchor I just placed just becomes un-teleportable to by both other anchors and staff of traveling

**Comment by Amaxter** [comment]
Either an issue with the server you're playing on or the mod. Test in SP, if still doesn't work then submit to the Ender IO GitHub please.

**Comment by hubb2001** [comment]
Tested in SP its a problem with config on the official core zero server

**Comment by Amaxter** [comment]
Ok, thanks for the info. Will fix when I get back.
