### ISSUE TITLE
screen distortion

### ISSUE THREAD

**Issue by davidjones2** [Amaxter/Core-Zero#27]
I'm getting an strange screen distortion when I load the game. When I reinstall it I have no problem with it but when I relaunch the game later I get the distortion. I have 4gb ram allocated and over 300 gb free space so that is not the problem.
video: http://gfycat.com/LikableAnnualCorydorascatfish

PC specs:
i5-2500k
8gb ram
nvidia 650 TI
ssd + 500gb hdd
Windows 7 ultimate

**Comment by Amaxter** [comment]
Try reinstalling OptiFine, that's rather odd. Doesn't happen in any other Minecraft instances?

**Comment by davidjones2** [comment]
1. I have removed optifine from the mod list but still have the issue. Thr first time I delte the pack and reinstall it I have no problem with it.
2. I have been playing modded minecraft for the last 3 years and this is the first time I have something like this.

I do know its not a problem with my pc parts because I'm able to run this pack above 100 fps.

**Comment by Amaxter** [comment]
It's not a widespread issue, my suspicion is it may be an issue with your drivers. Regardless, including this but will stay in touch just out of curiosity if you're able to fix it, and will let you know if I find anything :)
