### ISSUE TITLE
Fluid.oilgc

### ISSUE THREAD

**Issue by Cantose** [Amaxter/Core-Zero#28]
I am pumping oil into my ME network, I am finding the fluid listed is not recognized, and as such can't be moved out of the network once it's in. 

I am guessing this is an issue with the Mekanism oil conflicting with another oil in game.

When viewed in the Fluid window for my me network, the fluid is called fluid.oilgc.

I have done some minor troubleshooting to see if it's any recognizable fluid present in the game, and have not been successful.

Thanks

**Comment by Amaxter** [comment]
I'll look into the issue when I get back, thanks for bringing it to my attention.

**Comment by Amaxter** [comment]
Fixed by disabling all other oils except BuildCraft for next update.

**Comment by Cantose** [comment]
Thanks team!!

Best mod pack ever.
