### ISSUE TITLE
client crashes when i try to connect to the server 

### ISSUE THREAD

**Issue by anjorion** [Amaxter/Core-Zero#29]
evrytime i try to connect to the server my client crashes and i have no idee why. got this crash report, maybe it helps to fix the problem: 
http://pastebin.com/MkYWet3T

**Comment by Amaxter** [comment]
Details please. Has his always happened or has it just started to happen, does it happen on the official server only?

**Comment by anjorion** [comment]
it just started today on the official server after i used the grindstone from applied energistics to pulverise a gold ingot, but  now it works fine.
I just give the game less ram i had 10 gb ram used on the client now i use 4 gb ram and it works fine now 
maybe its the amount of ram i use or a rollback fixed it im not sure.
