### ISSUE TITLE
I keep crashing every time I join the server

### ISSUE THREAD

**Issue by druv5319** [Amaxter/Core-Zero#3]
Whenever I log on the server, my whole modpack crashes then closes. So I cant play
Logs: http://pastebin.com/QQnwp91U
Crash Report: http://pastebin.com/trGbE9jp

And yes i did try to uninstall optifine and it still kept crashing

**Comment by Amaxter** [comment]
Try updating your graphics drivers. Regardless, this isn't a modpack issue, it's a problem on your end. Good luck.

**Comment by druv5319** [comment]
What if I have a laptop in which the graphics driver cant be replaced

**Comment by Amaxter** [comment]
Graphics drivers aren't hardware, they're a software download that is executed.
