### ISSUE TITLE
Crashing on Join.

### ISSUE THREAD

**Issue by TheChiller12** [Amaxter/Core-Zero#31]
Topic says it all. Will attach a pastebin for the log later.

**Comment by Amaxter** [comment]
Please do :)

**Comment by TheChiller12** [comment]
http://pastebin.com/hFbf2sUZ

**Comment by Amaxter** [comment]
Let me attempt to reset your player's position (all your other player data will be kept).

**Comment by Amaxter** [comment]
Please attempt to join now.

**Comment by TheChiller12** [comment]
Thanks, seems like the new Draconic Evolution may have broken the Enhanced Charm of Dislocation, that or either the reset did it.

**Comment by TheChiller12** [comment]
I did, reset me back to spawn. Thanks!

**Comment by Amaxter** [comment]
No problem!
