### ISSUE TITLE
RFTools Removed?

### ISSUE THREAD

**Issue by TheChiller12** [Amaxter/Core-Zero#32]
Is this a bug or was it removed?

EDIT #1 Looks Like it was removed. Amaxter reopen this if it is a glitch,

**Comment by Amaxter** [comment]
Oh shit, I made a mistake.

**Comment by TheChiller12** [comment]
RIP

**Comment by Amaxter** [comment]
Hold on, almost fixed.

**Comment by TheChiller12** [comment]
I'll be here. :)

**Comment by Amaxter** [comment]
Fixed, install 1.1.2a in your launcher, server is restarting now.

**Comment by TheChiller12** [comment]
1.1.2a? or 1.2.2a?

**Comment by Amaxter** [comment]
1.2.2a another mistake lol :P

**Comment by TheChiller12** [comment]
It's fine. :)

**Comment by Amaxter** [comment]
Enjoy the update :)

**Comment by TheChiller12** [comment]
https://gyazo.com/0f3b277e5e61483771f2b291d6188fc3
FML Issue. Will send you the log in a second.

**Comment by Amaxter** [comment]
Joy. Hold on.

**Comment by TheChiller12** [comment]
Log is too big to put into pastebin, lags out my browser. If you really need it, I'll send you a mediafire.

**Comment by Amaxter** [comment]
No need, install version 1.2.2b

**Comment by TheChiller12** [comment]
RFTools works, and issue fixed! Good job, Amaxter!

**Comment by Amaxter** [comment]
Well, I made a really dumb mistake, but at least I wasn’t THAT slow in fixing it :P

**Comment by TheChiller12** [comment]
:P

**Comment by TheChiller12** [comment]
All RFTools blocks were removed...
