### ISSUE TITLE
RFTools All blocks/EMC storage removed.

### ISSUE THREAD

**Issue by TheChiller12** [Amaxter/Core-Zero#33]
Not really that big of an issue to me, but who knows... I moved out of my dimensions, soo...

**Comment by Amaxter** [comment]
Sorry about that, I can try restoring from a backup if you really want. Regardless, keep in mind this is typically a place for modpack issues, not official server issues, so I will close.

**Comment by TheChiller12** [comment]
Just notifying you, not really asking for a solution. :) It was just bad luck that the server saved as soon as you first updated to 1.2.2 when RFTools wasn't there.

**Comment by Amaxter** [comment]
Thanks for notifying me.
