### ISSUE TITLE
Chunks Flashing in and out

### ISSUE THREAD

**Issue by poetofsilence** [Amaxter/Core-Zero#4]
Hey guys,

Recently, and not every time I load the game, I have been having issues with chunks flashing in and out. Its hard to explain but it looks like what xray mods look like, or when you walk somewhere that hasn't rendered yet. You can see the lava and caves under the ground, but the ground is still there. MOST of the time it fixes with a restart. Just thought you guys should know.

**Comment by Amaxter** [comment]
Sounds like a graphics issue. Try removing OptiFine, also make sure you have the latest version of Java and have a decent CPU as world gen is one of the most resource intensive things in Minecraft.

**Comment by poetofsilence** [comment]
It seemed to have something to do with the chunk loading setting in the options menu. Once those were set to default or smooth it ran fine. Just FYI.

**Comment by Amaxter** [comment]
Ok, glad you fixed it.
