### ISSUE TITLE
1.1.6a is not updated on the Server Files

### ISSUE THREAD

**Issue by desagas** [Amaxter/Core-Zero#5]
You updated the regular, single player files to 1.1.6a, but you failed to make the same updates to the server downloads. Therefore, downloading both, and trying to run a server causes it to crash because the mods do not match. Can you please fix this. Thanks

**Comment by Amaxter** [comment]
Uploaded, thanks for notifying me.

**Comment by desagas** [comment]
Thanks so much. I also wanted to let you know that Equivalent Energistics was updated to 0.3 now. Incase you have not seen. I only mention it because I know how many people are having issues with it crashing worlds while crafting.

**Comment by Amaxter** [comment]
Thanks for letting me know, saw it on CurseForge :)
