### ISSUE TITLE
Keep crashing again

### ISSUE THREAD

**Issue by druv5319** [Amaxter/Core-Zero#7]
I was fine playing for a while now, but whenever I spawn in the server at my base, my whole minecraft crashes after 1 minute of playing

Crash Report: http://pastebin.com/ywQX7Fi8

**Comment by xJon** [comment]
Try to manually remove Optifine, and then test again. Is there any change?

**Comment by druv5319** [comment]
That still didnt work

**Comment by Amaxter** [comment]
What's your UUID? You can find it at http://mcuuid.net

**Comment by druv5319** [comment]
d446c1c8-ea3a-4bdb-a3f8-ac48ecef6880

Whats this for?

**Comment by Amaxter** [comment]
We're going to reset your playerdata. You'll lose everything you had on the server, but the other option is not being able to play.

**Comment by druv5319** [comment]
wait, I went to spawn when i spawned at my base, it didnt crash this time, and when I went /home it didnt crash either. I think it is when I spawn on the server at my base, this usually happend

**Comment by druv5319** [comment]
And dont reset my player data

**Comment by Amaxter** [comment]
Ok, good closing this issue :)

**Comment by druv5319** [comment]
Wait, One more thing, can you fix the rollback issue on the server? whenever it crashes, the whole server has a rollback. I made a tinkers longsword before it, and then once it rolledback It was gone. And the resources were also gone too.

**Comment by Amaxter** [comment]
Likely just lag, will look into it.

**Comment by druv5319** [comment]
Yeah, It keeps happening again max. Can you add staff or something?

**Comment by Amaxter** [comment]
Staff are busy on our other servers. Will look into the crashes soon.
