### ISSUE TITLE
Special Mobs has deleted regular Wither Skeletons

### ISSUE THREAD

**Issue by desagas** [Amaxter/Core-Zero#9]
Regular wither skeletons drop necrotic bones. So currently, there is not way to get necrotic bones in this pack. I have heard of a config file fix to prevent this, allowing some original wither skeletons to spawn. However, this would not be a problem if regular skeletons spawned as well, because we could witch water them into withers, but again, sadly, special mobs has removed all the original spawns for skeletons of all types.

**Comment by Amaxter** [comment]
Ok, I'll look into letting Wither Skeletons spawn.

**Comment by Amaxter** [comment]
Thanks Jon!
